name: CI Workflow

on:
  push:
    branches:
      - main  # Aciona o workflow quando houver push para a branch main
  pull_request:
    branches:
      - main  # Aciona o workflow quando houver pull request para a branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Sistema operacional que o GitHub Actions usará

    steps:
      - name: Checar o código
        uses: actions/checkout@v2  # Faz o checkout do código do repositório

      - name: Configurar o Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Define a versão do Python que você deseja usar

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala as dependências do projeto, se houver um arquivo requirements.txt

      - name: Rodar os testes
        run: |
          pytest  # Roda os testes (ajuste isso conforme a sua necessidade)
